ALTER PROCEDURE [dbo].[GL_GWY_DELETE_Person](@WHERE_SQLSTR VARCHAR(MAX))
AS
BEGIN
	-- 创建条件临时表
	EXEC dbo.GS_SMCheckDropTable #WHERE_SCOPE_PERSONID
	CREATE TABLE #WHERE_SCOPE_PERSONID
	(
		PersonID VARCHAR(36)
	)
	-- 把人员范围插入临时表
	INSERT INTO #WHERE_SCOPE_PERSONID EXEC (@WHERE_SQLSTR)
	--SELECT * FROM #WHERE_SCOPE_PERSONID
	
	DECLARE
		@DBID INT,
		@SetID VARCHAR(100),
		@RealSetID VARCHAR(1000),
		@SQL VARCHAR(8000)
	
	-- 声明游标
	DECLARE
		CURSOR_SETCHILD CURSOR
	    FOR (SELECT DBID, SetID, RealSetID FROM SM_SetTable WHERE DBID IN (1, 21) AND Selected = 1)
	    
	OPEN CURSOR_SETCHILD; 
	FETCH NEXT FROM CURSOR_SETCHILD INTO @DBID, @SetID, @RealSetID;
	
	WHILE @@FETCH_STATUS = 0
	BEGIN
		SET @SQL =
			CASE @DBID
				WHEN 1 THEN 
					'DELETE FROM '+ @RealSetID +' WHERE PersonID IN (SELECT PersonID FROM #WHERE_SCOPE_PERSONID)'
				WHEN 21 THEN 
					'DELETE FROM '+ @RealSetID +' WHERE '+ @SetID +'PersonID IN (SELECT PersonID FROM #WHERE_SCOPE_PERSONID)'
				ELSE '-1'
			END
		
		IF @SQL <> '-1'
		BEGIN
			EXEC (@SQL)
		END
		
		--PRINT @SQL
	    FETCH NEXT FROM CURSOR_SETCHILD INTO @DBID, @SetID, @RealSetID;
	END
	CLOSE CURSOR_SETCHILD;
	DEALLOCATE CURSOR_SETCHILD;
END
GO

